name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-unit-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependancies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display my username (ngfRt)
      run: echo "ngfRt"
  run-ui-tests:
    runs-on: ubuntu-latest
    needs: build-and-run-unit-test
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependancies
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Start the app
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui

  deploy:
    runs-on: ubuntu-latest
    needs: run-ui-tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          # wait-for-success: true